### PR TITLE
QUICKFIX Duplicate Sign In

### PR DESCRIPTION
**Pull request by rayliverified**
*Remove duplicated sign in call.

### CODE REVIEW

**Comment by rayliverified** [comment]
This is a good start, thanks for sharing your project. 

`createUserWithEmailAndPassword` takes care of the sign in for you. 

> If successful, it also signs the user in into the app and updates the [onAuthStateChanged] stream.

**Comment by rayliverified** [comment]
Were you able to test web auth from localhost? I ran into an unauthorized domain error and didn't have much luck after that.

**Comment by delay** [comment]
Thanks for the pull request.  I didn't know firebase automatically logged the user in after creating them.  As far as web auth not working from localhost... What exactly are you trying to do?  I have no problem running the web version from my local computer.  A few things to look at.  Did you setup your project? https://firebase.google.com/docs/flutter/setup  Also maybe see the last comment posted here.  https://github.com/firebase/firebaseui-web/issues/141

**Comment by delay** [comment]
Also make sure you put your own config info in /web/index.html

**Comment by rayliverified** [comment]
Thanks for merging @delay 
You'll likely run into the localhost issue when you try using an OAuth provider like Google SignIn.

**Comment by delay** [comment]
Ahh ok... I never completed the google signin and other authorizations.  I do not currently use them when building my own apps and I am currently working on a new project.  I may revisit adding those in the future, but it will be a while.  These two guys have good tutorials that might go over this.  https://codewithandrea.com/ and https://fireship.io

**Comment by rayliverified** [comment]
No worries! I've got them working, just not the localhost part. 
Thanks again for sharing this repo!

**Pull request merged**
